#!/bin/bash

# Get Volume
get_volume() {
	volume=`wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2}'`
	
	if [[ "$volume" == "[Muted]" ]]; then
		echo "Mute"
	else
		percent=$(echo "$volume * 100" | bc)
		echo "$percent"
	fi
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	if [[ "$current" -eq "0" ]]; then
		echo "images/icons/audio/mute.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "images/icons/audio/volume.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "images/icons/audio/volume.png"
	elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
		echo "images/icons/audio/volume.png"
	fi
}


# Increase Volume
inc_volume() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
}

# Decrease Volume
dec_volume() {
	wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
}

# Toggle Mute
toggle_mute() {
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
}
SINK=${SINK:-@DEFAULT_AUDIO_SINK@}

set_volume() {
  # $1 is 0-100 from Eww. Convert to 0-1 for wpctl.
  local pct="${1%.*}"                         # strip decimals if any
  local val
  val=$(awk -v v="$pct" 'BEGIN{printf "%.4f", v/100}')
  # unmute when setting volume
  wpctl set-mute "$SINK" 0
  wpctl set-volume "$SINK" "$val"
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "--inc" ]]; then
	inc_volume
elif [[ "$1" == "--dec" ]]; then
	dec_volume
elif [[ "$1" == "--set" ]]; then
	set_volume "$2"
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi
